/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/risk/curvebucketer.hpp>
#include <ql/risk/frtbsagirr.hpp>
#include <ql/risk/xvacalculator.hpp>
