/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/marketdata/csvquoteloader.hpp>
#include <ql/marketdata/jsonquoteloader.hpp>

